// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXnJcZdLvYxJdDDefnNWKOZQY0U4ID_fQ',
    appId: '1:181643105640:web:6289c234b641f14d97b2dd',
    messagingSenderId: '181643105640',
    projectId: 'manhua-app-cb330',
    authDomain: 'manhua-app-cb330.firebaseapp.com',
    storageBucket: 'manhua-app-cb330.firebasestorage.app',
    measurementId: 'G-FVGHSNZHC7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1PHQgH3gBecsVSET5dzl3LTbv8lBo7mA',
    appId: '1:181643105640:android:c661ad63e5367d9a97b2dd',
    messagingSenderId: '181643105640',
    projectId: 'manhua-app-cb330',
    storageBucket: 'manhua-app-cb330.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo64aYkO7zj0PVXf6eKyNWJ63WvxA63o8',
    appId: '1:181643105640:ios:7fac3098bdbd9c4397b2dd',
    messagingSenderId: '181643105640',
    projectId: 'manhua-app-cb330',
    storageBucket: 'manhua-app-cb330.firebasestorage.app',
    iosBundleId: 'com.example.mangaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo64aYkO7zj0PVXf6eKyNWJ63WvxA63o8',
    appId: '1:181643105640:ios:7fac3098bdbd9c4397b2dd',
    messagingSenderId: '181643105640',
    projectId: 'manhua-app-cb330',
    storageBucket: 'manhua-app-cb330.firebasestorage.app',
    iosBundleId: 'com.example.mangaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXnJcZdLvYxJdDDefnNWKOZQY0U4ID_fQ',
    appId: '1:181643105640:web:fd7802bf85cc529797b2dd',
    messagingSenderId: '181643105640',
    projectId: 'manhua-app-cb330',
    authDomain: 'manhua-app-cb330.firebaseapp.com',
    storageBucket: 'manhua-app-cb330.firebasestorage.app',
    measurementId: 'G-SWBKFJ6R8W',
  );

}